user_learning/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from userapp.views import index
from userapp import views
urlpatterns = [
    # path('base/',views.base,name='base'),
    path('admin/', admin.site.urls),
    # url(r'^$',views.index,name='index'),
    # url(r'^userapp/$',include('userapp.urls'))
    path('',views.index,name='index'),
    
    path('userapp/',include(('userapp.urls','userapp'),namespace="userapp")),

    path('special',views.special,name='special'),

]

userapp/urls.py
from django.conf.urls import url
from django.urls import path
from userapp import views


         

#TEMPLATES URLS!
# app_name='userapp'
# appname variable

urlpatterns=[

path('register/',views.register,name='register'),
path('withlogin/',views.withlogin, name= 'withlogin'),
path('user_login/',views.user_login,name='user_login'),
path('logout/',views.user_logout,name='user_logout'),

]

userapp/models.py
from django.db import models
from django.contrib.auth.models import User #this is the builtin user--present in admin page

# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)

    #additional
    handle = models.CharField(max_length=100,blank=True)


    # ie the uploaded images will be saved under 'profile_pics' in media folder

    def __str__(self):
        return self.user.username

class tweets(models.Model):
    tw = models.TextField()
    reciever = models.ForeignKey(User,on_delete = models.CASCADE)
    sender = models.CharField(max_length = 200)
    reported = models.BooleanField(default = 0)
    date = models.DateTimeField(auto_now = True)



class TotalClassified(models.Model):
    number = models.IntegerField(default = 0)
    total_reported = models.IntegerField(default=0)

userapp/forms.py
from django import forms
from django.contrib.auth.models import User
from . models import UserProfileInfo

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model =User
        fields=('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model= UserProfileInfo
        fields=('handle',)

class SearchForm(forms.Form):
    search  = forms.CharField(max_length = 200)

userapp/views.py
from django.shortcuts import render,redirect
from .forms import UserForm, UserProfileInfoForm,SearchForm
from django.contrib.auth.models import User
import tweepy
import threading ,time
import re
import pandas as pd
import nltk
import pickle
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from nltk import WordNetLemmatizer
from nltk.corpus import stopwords
import requests
from .models import tweets,TotalClassified
# for login..
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
# from django.core.urlresolvers import reverse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render
from django.views import View
import tweepy
import threading ,time
import re
import pandas as pd
import nltk
import pickle

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from nltk import WordNetLemmatizer
from nltk.corpus import stopwords
import requests
from django.shortcuts import get_object_or_404


# Create your views here.
def withlogin(request):
     posts = tweets.objects.filter(reciever = request.user).order_by('date')
     print(posts)
     number = get_object_or_404(TotalClassified,id=2)
     reported = get_object_or_404(TotalClassified,id=2)
     
     users =  User.objects.all().count()
     miss = 5
     print(number)
     print(reported)
     context = {
'posts':posts,
'number':number,
'total_reported':reported,
'users':users,
'miss':miss,
     }
     return render(request, 'userapp/withlogin.html' ,{})


def model_proc(query):
    if not query:
        query = "@realDonaldTrump"
    badwords = []
    bow = pickle.load(open("C:/Users/Grindelwald/Desktop/tweeter/App1/tfidf.pickle",'rb'))
    dct = pickle.load(open("C:/Users/Grindelwald/Desktop/tweeter/App1/finalized_model1.sav",'rb'))
    for line in open("C:/Users/Grindelwald/Desktop/tweeter/App1/badwords.txt"):
            for word in line.split( ):
                badwords.append(word)
    consumer_secret = 'Y7xcl4yvOzHCbUG1lQo6KcuX9CocVFwaO8pEp2QCI70Yh1jxuS'
    consumer_key = 'FtdxPkwxNycQsoff0YyBT6mhr'
    access_token = '808233723481100288-DreiznXUXvFUJ25CUkbe3pcmixsa4ia'
    access_token_secret = 'rD9qXxwt51rdUqgX8FbSCHgGJCMAt3THevNxYpKJd6j9G'
    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_token, access_token_secret)
    api = tweepy.API(auth)
    twe = []
    results = []
    for tweet in tweepy.Cursor(api.search, q=query,tweet_mode='extended').items(10):
         
        
        if hasattr(tweet, 'retweeted_status'):
         
            tw = tweet.retweeted_status.full_text
            msg = model_process(tweet.retweeted_status.full_text,badwords)
            if(msg==1):
                result = 1
            
            else:
                bow_matrix = bow.transform([msg])
                df_bow = pd.DataFrame(bow_matrix.todense())
                result  =dct.predict(df_bow)
            print(result)

        else:
            tw = tweet.full_text

            msg = model_process(tweet.full_text,badwords)
            if(msg==1):
                result = 1
            
            else:
                bow_matrix = bow.transform([msg])
                df_bow = pd.DataFrame(bow_matrix.todense())
                result  =dct.predict(df_bow)
        twe.append(tw)
        results.append(result)
        
        if result=='[1]' or result == 1:
              user = User.objects.get(username= "Donald_Trump")
              tweets.objects.create(reciever = user,tw= tw,sender ="@nickson" )

    
    return twe,results






    

def model_process(text,badwords):
    pattern = "@[\w]*"
    
    r=  re.findall(pattern,text)
    
    for i in r:
        text = re.sub(i,"",text)
    text = ' '.join([w for w in text.split() if w.lower() not in stopwords.words('english')])
    text = ' '.join(re.sub("(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)", " ", text).split())
    x = text.split()
    for word in x:
        if word in badwords:
            return 1
    
    
    return text

@csrf_exempt
def register(request):
    registered= False
    if request.method=='POST':
        
        user_form= UserForm(data=request.POST)
        profile_form =UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)    #pws saved via hashing
            user.save()

            profile = profile_form.save(commit=False)   #commit=False since we've to check if the pic is there or not before saving it
            profile.user=user   #this is setting the OneToOne relationship in views as it was in models

            # now checking if they provided a profile picture or not

    else:
        
        user_form =  UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'userapp/registration.html',
                            {'user_form':user_form,
                            'profile_form':profile_form,
                            'registered':registered})


@csrf_exempt
def user_login(request):


    if request.method == 'POST':
        username = request.POST.get('username') #since we've given user name as -->name="username" in login.html
        password = request.POST.get('password')


        user= authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                
                return render(request,'userapp/withlogin.html')
                # return HttpResponseRedirect(reverse('index'))

            else:
                # return HttpResponse("Account Not active")
                return HttpResponseRedirect(reverse('user_login'))
        else:
            print("Someone tried to login and failed!")
            print("Username: {} and password{}".format(username,password))
            return HttpResponse('invalid login details supplied!')
    else:
        return HttpResponseRedirect(reverse('withlogin'))

@login_required
def special(request):
    return HttpResponse("You are logged in..;-)")



@login_required
def user_logout(request):
    logout(request)
    return render(request,'userapp/index.html',{})




def index(request):
    
    form = SearchForm(request.POST or None)
    if request.method == 'POST':
        q =  request.POST['search']
        print(q)
        print("-----------------------------------------")
        result,tweet = model_proc(q)
        posts = tweets.objects.all().order_by('date')
        classify = get_object_or_404(TotalClassified,id=2)
        
     
        users =  User.objects.all().count()
        miss = 5
        
        context = {'data': zip(result, tweet),'posts':posts, 'classify':classify,'users':users,'miss':miss,}
        return render(request,"userapp/withoutlogin.html",context)
   

    posts = tweets.objects.all().order_by('date')
    classify = get_object_or_404(TotalClassified,id=2)
    users =  User.objects.all().count()
    miss = 5
   
    context = {'classify':classify,'users':users,'miss':miss,'form':form,'posts':posts, }
    return render(request,"userapp/index.html",context)

templates/userapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
<style>
  .drop_width
  {
    width:400px;
  }
  {
  box-sizing: border-box;
}

/* Style the search field */
form.example input[type=text] {
  padding: 10px;
  font-size: 17px;
  border: 1px solid grey;
  float: left;
  width: 80%;
  background: #f1f1f1;
}

/* Style the submit button */
form.example button {
  float: left;
  width: 20%;
  padding: 10px;
  background: #2196F3;
  color: white;
  font-size: 17px;
  border: 1px solid grey;
  border-left: none; /* Prevent double borders */
  cursor: pointer;
}

form.example button:hover {
  background: #0b7dda;
}

/* Clear floats */
form.example::after {
  content: "";
  clear: both;
  display: table;
}
</style>
<body>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
    <!-- without above 3 scripts toggler button wasnt clickable -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
<link rel="shortcut icon" type="image/png" href="{% static '/userapp/favicon.ico' %}"/>


    <!-- Custom fonts for this template-->
    <link href="{% static 'userapp/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">


  </head>
 {% if not user.is_authenticated %}
  <nav class="navbar navbar-expand-lg ftco_navbar  ftco-navbar-light" id="ftco-navbar">
        <div class="container">


          <div class="collapse navbar-collapse" id="ftco-nav">
                <ul class="navbar-nav ml-auto">
                <li class="nav-item "><a href ="{% url "userapp:register" %}" class="nav-link">Register</a></li>
                <li class="nav-item"><a href ="{% url "userapp:user_login" %}"class="nav-link">LogIn</a></li>

                </ul>
          </div>
        </div>
      </nav>
{% endif %}



      {% block body_block %}


      {% endblock %}



      <!-- Core plugin JavaScript-->

      <!-- Custom scripts for all pages-->


      <!-- Page level plugins -->
      <script src="{% static '/userapp/js/demo/chart-area-demo.js' %}"></script>

      <!-- Page level custom scripts -->
      <script src=""></script>
      <script src="{% static 'userapp/js/demo/chart-pie-demo.js' %}"></script>

    <script src="{% static 'userapp/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'userapp/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'userapp/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'userapp/js/sb-admin-2.min.js' %}"></script>

  </body>

</html>

templates/userapp/dashboard.html
{% extends 'userapp/base.html' %}

{% block body_block %}

<div class="jumbotron">
  <h1>Dashboard</h1>

</div>

{% endblock %}

templates/userapp/l.html
<html>
<head>
  </head>
  <body>
    </body>
</html>

templates/userapp/login.html
{% extends 'userapp/base.html' %}

{% block body_block %}

    <div class="drop_width">
  <div class="col-lg-12">
        <div class="text-center"><h3><b>Log In</b></h3></div>

        <form class='user' action="{% url 'userapp:user_login' %}" method="POST">

          {% csrf_token %}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
    <br><br>
          <label for="password">Password:</label>
          <input type="password" name="password">
    <br><br>
          <input class="btn btn-primary btn-user btn-block" type="submit" value="Login">
        </form>

        <ul class="dropdown-menu dropdown-menu-right dropdown-lr animated slideInRight" role="menu">
            <div class="drop_width">
          <div class="col-lg-12">
                <div class="text-center"><h3><b>Log In</b></h3></div>
{% endblock %}







        <form id="ajax-login-form" action="http://phpoll.com/login/process" method="post" role="form" autocomplete="off">
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" name="username" id="username" tabindex="1" class="form-control" placeholder="Username" value="" autocomplete="off">
            </div>

            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Password" autocomplete="off">
            </div>

            <div class="form-group">
                <div class="row">

                    <div class="col-xs-5 pull-right">
                        <input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-success" value="Log In">
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-center">
                            <a href="http://phpoll.com/recover" tabindex="5" class="forgot-password">Forgot Password?</a>
                        </div>
                    </div>
                </div>
            </div>
            <input type="hidden" class="hide" name="token" id="token" value="a465a2791ae0bae853cf4bf485dbe1b6">
        </form>
    </div>
  </div>
</ul>

templates/userapp/registration.html
{% extends 'userapp/base.html' %}

{% load static %}
{% load crispy_forms_tags %}
{% block body_block %}
{% if registered %}
  <h1>Thank you for registration!</h1>
  <p>ihuhj</p>
  <<a href="#"></a>
{% else %}

 <!-- <ul class="dropdown-menu dropdown-menu-right dropdown-lr animated flipInX" role="menu"> -->
  <div class="drop_width">
  <div class="col-lg-12">
        <div class="text-center"><h3><b>Register</b></h3></div>
        <form method='POST' action = '' class='user'>
          {% csrf_token %}
        {{user_form.as_p}}
        {{ profile_form.as_p}}









          <input type="submit" class="btn btn-primary btn-user btn-block" name="" value="Register">
        </form>
          <a class="small" href="{% url 'userapp:user_login' %}">Already have an account? Login!</a>
    </div>
    </div>
</ul>
</li>

<li class="dropdown">



  {% endif %}
  {% endblock %}

templates/userapp/withlogin.html
{% extends 'userapp/base.html' %}
{% load static %}
{% block body_block %}
<!-- Page Wrapper -->
<div id="wrapper">


  <!-- Content Wrapper -->
  <div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">

      <!-- Topbar -->
      <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i>Report</a>


        <!-- Topbar Navbar -->
        <ul class="navbar-nav ml-auto">

          <div class="topbar-divider d-none d-sm-block"></div>

          <!-- Nav Item - User Information -->
          <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="mr-2 d-none d-lg-inline text-gray-600 small">Valerie Luna</span>
              <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
              <a class="dropdown-item" href="#">
                <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                Profile
              </a>
              <a class="dropdown-item" href="#">
                <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                Settings
              </a>
              <a class="dropdown-item" href="#">
                <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                Activity Log
               </a>
              <div class="dropdown-divider"></div>

              <a class="dropdown-item" href="{% url 'userapp:user_logout' %}" data-toggle="modal" data-target="#logoutModal"> Logout   <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i></a>
            </div>
          </li>

        </ul>

      </nav>
      <!-- End of Topbar -->

      <!-- Begin Page Content -->
      <div class="container-fluid">

        <!-- Page Heading -->

          <!-- Content Row -->
            <div class="row">

          <!-- Earnings (Monthly) Card Example -->
          <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
              <div class="card-body">
                <div class="row no-gutters align-items-center">
                  <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Registers</div>
                    <div class="h5 mb-0 font-weight-bold text-gray-800">{{users}}</div>
                  </div>
                  <div class="col-auto">
                    <i class="fas fa-calendar fa-2x text-gray-300"></i>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <!-- Earnings (Monthly) Card Example -->
          <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-success shadow h-100 py-2">
              <div class="card-body">
                <div class="row no-gutters align-items-center">
                  <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-success text-uppercase mb-1">MissClassified</div>
                    <div class="h5 mb-0 font-weight-bold text-gray-800">{{miss}}</div>
                  </div>
                  <div class="col-auto">
                    <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <!-- Earnings (Monthly) Card Example -->
          <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-info shadow h-100 py-2">
              <div class="card-body">
                <div class="row no-gutters align-items-center">
                  <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Negatives</div>
                    <div class="row no-gutters align-items-center">
                      <div class="col-auto">
                        <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{classify.number}}</div>
                      </div>
                      <div class="col">
                        <div class="progress progress-sm mr-2">
                          <div class="progress-bar bg-info" role="progressbar" style="width: 75%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-auto">
                    <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <!-- Pending Requests Card Example -->
          <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
              <div class="card-body">
                <div class="row no-gutters align-items-center">
                  <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Reported</div>
                    <div class="h5 mb-0 font-weight-bold text-gray-800">{{classify.total_reported}}</div>
                  </div>
                  <div class="col-auto">
                    <i class="fas fa-comments fa-2x text-gray-300"></i>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Content Row -->

        <div class="row">

          <!-- Area Chart -->
          <div class="col-xl-8 col-lg-7">
            <div class="card shadow mb-4">
              <!-- Card Header - Dropdown -->
              <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Earnings Overview</h6>
              </div>
              <!-- Card Body -->
              <div class="card-body">
                <div class="chart-area">
                  <canvas id="myAreaChart"></canvas>
                </div>
              </div>
            </div>

            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Revenue Sources</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                      <div class="dropdown-header">Dropdown Header:</div>
                      <a class="dropdown-item" href="#">Action</a>
                      <a class="dropdown-item" href="#">Another action</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                  <div class="chart-pie pt-4 pb-2">
                    <canvas id="myPieChart"></canvas>
                  </div>
                  <div class="mt-4 text-center small">
                    <span class="mr-2">
                      <i class="fas fa-circle text-primary"></i> Positive
                    </span>
                    <span class="mr-2">
                      <i class="fas fa-circle text-success"></i> Negative
                    </span>
                    <span class="mr-2">
                      <i class="fas fa-circle text-info"></i> Neutral
                    </span>
                  </div>
                </div>
              </div>

          </div>

          <!-- Pie Chart -->
          <div class="col-xl-4 col-lg-5">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                  <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                      <thead>
                        <tr>
                          <th>Username</th>
                          <th>tweet</th>
                        </tr>
                      </thead>
                      <tbody>
                        {%for post in posts%}
                        <tr>
                          <td>{{post.sender}}</td>
                          <td>{{post.tw}}</td>
                        </tr>
                        {%endfor%}
                      </tbody>
                    </table>
                  </div>
                </div>

          </div>
        </div>
      </div>



        <!-- Content Row -->

        <div class="row">
            <div class="col-xl-6 col-lg-5">
                <div class="card shadow mb-4">
                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                        <h6 class="m-0 font-weight-bold text-primary">Image 1</h6>
                    </div>
                    <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
                </div>
            </div>

            <div class="col-xl-6 col-lg-5">
                <div class="card shadow mb-4">
                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                        <h6 class="m-0 font-weight-bold text-primary">Image 2</h6>
                    </div>
                    <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
                </div>
            </div>
        </div>

      <!-- /.container-fluid -->

    </div>
    <!-- End of Main Content -->

    <!-- Footer -->
    <footer class="sticky-footer bg-white">
      <div class="container my-auto">
        <div class="copyright text-center my-auto">
          <span>Copyright &copy; Your Website 2019</span>
        </div>
      </div>
    </footer>
    <!-- End of Footer -->

  </div>
  <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
  <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
        <a class="btn btn-primary" href="{% url 'userapp:user_logout' %}">Logout</a>
      </div>
    </div>
  </div>
</div>

{% endblock %}